server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://gateway:8080/;
    }

    location /py-api/ {
        proxy_pass http://python-api:8000/;
    }

    location / {
        try_files $uri /index.html;
    }
}
